# Generated by Django 5.2.5 on 2025-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
