# Generated by Django 4.2.16 on 2025-09-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='duration',
            field=models.FloatField(default=1.0, help_text='Duration in hours'),
        ),
    ]
