# Generated by Django 4.2.16 on 2025-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduleevent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
