# Generated by Django 4.2.16 on 2025-09-17 15:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_scheduleevent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='series_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
