# Generated by Django 4.2.16 on 2025-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_scheduleevent_series_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='color',
            field=models.CharField(blank=True, default='blue', max_length=20),
        ),
    ]
