# Generated by Django 4.2.16 on 2025-10-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_scheduleevent_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleevent',
            unique_together=set(),
        ),
    ]
