# Generated by Django 4.2.16 on 2025-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_scheduleevent_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleevent',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
