# Generated by Django 4.2.16 on 2026-09-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='status',
            field=models.CharField(choices=[('note', 'Заметка'), ('individual', 'Индивидуальное занятие'), ('group', 'Групповое занятие')], db_index=True, default='note', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='events', to='scheduler.student', verbose_name='Ученики'),
        ),
    ]
