# Generated by Django 4.2.16 on 2026-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_scheduleevent_status_scheduleevent_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда отмечено'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('passed', 'Прошло успешно'), ('missed_student', 'Пропущено учеником'), ('missed_teacher', 'Пропущено преподавателем'), ('not_conducted', 'Не проведено')], db_index=True, default='', max_length=20, verbose_name='Статус проведения'),
        ),
    ]
