# Generated by Django 4.2.16 on 2026-09-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_scheduleevent_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_present', models.BooleanField(verbose_name='Присутствовал')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда отмечено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduler.scheduleevent', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduler.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'indexes': [models.Index(fields=['event', 'student'], name='scheduler_a_event_i_5c7c67_idx'), models.Index(fields=['student', 'was_present'], name='scheduler_a_student_517e36_idx')],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
