# Generated by Django 4.2.16 on 2026-09-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCoursePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_lesson', models.IntegerField(default=0, verbose_name='Цена за занятие (₽)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_prices', to='scheduler.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prices', to='scheduler.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Цена ученика за курс',
                'verbose_name_plural': 'Цены учеников за курсы',
                'ordering': ['course__name'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
