# Generated by Django 4.2.16 on 2026-09-26 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0015_studentcourseprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма (₽)')),
                ('operation_type', models.CharField(choices=[('payment', 'Оплата'), ('charge', 'Списание за занятие'), ('adjustment', 'Корректировка')], db_index=True, max_length=20, verbose_name='Тип операции')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_operations', to='scheduler.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_operations', to='scheduler.scheduleevent', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_operations', to='scheduler.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Операция по балансу',
                'verbose_name_plural': 'Операции по балансу',
                'ordering': ['-operation_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'course'], name='scheduler_b_student_4d05f6_idx'), models.Index(fields=['operation_type'], name='scheduler_b_operati_0d1206_idx')],
            },
        ),
    ]
