# Generated by Django 4.2.16 on 2026-09-27 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_balanceoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scheduler.course', verbose_name='Курс'),
        ),
    ]
