# Generated by Django 4.2.16 on 2026-09-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_scheduleevent_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_operations', to='scheduler.scheduleevent', verbose_name='Занятие'),
        ),
    ]
