# Generated by Django 5.2.17 on 2026-09-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_student_birth_date_student_extra_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='compensated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Компенсация предоставлена'),
        ),
    ]
