# Generated by Django 5.2.17 on 2026-10-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_attendance_compensated'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='compensation_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensating_events', to='scheduler.attendance', verbose_name='Отработанный пропуск'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='is_compensation',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Компенсация'),
        ),
    ]
