# Generated by Django 5.2.17 on 2026-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_scheduleevent_compensation_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='compensation_attendance',
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='compensation_attendances',
            field=models.ManyToManyField(blank=True, related_name='compensating_events', to='scheduler.attendance', verbose_name='Отработанные пропуски'),
        ),
    ]
